version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

  capistrano:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          # RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      #deploy
      - add_ssh_keys:  
          fingerprints:  
            - 4a:dd:86:24:18:c1:03:ea:da:29:8f:6d:34:32:79:17
      - run:  
          name: docker-compose stop
          command: docker-compose stop
      - deploy:  
          name: Deploy with Capistrano
          command: cap production deploy  

workflows:
  version: 2
  build:
    jobs:
      - rubocop
      - rspec
      - capistrano:
          requires:
            - rspec
            - rubocop
            